# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e2945a9d1a3d9fac3dbd500a8a8b6f6117f189fc0256e11e95437f5b123c409cb6bb2fe6cec3e5b1b188c11667b78a7362dcacdc16751c7cb65c87ae98502d4
  firebase_pn_key: AAAAK1R4_qE:APA91bHfn_BW-vAkjKWulUmrEHiU0kjG2t4W5SyVo30xzit8VXENwmfD59nHE07Hlr0YBm_7EBxbfQWLfyjsc55Qt4MBLqssNEMyIGgGubsRFRAy9LpV3n_PTy-7sOk_2x6JJnpjSfTv

test:
  secret_key_base: 99cd5382b835a14bc646d684766b55ee369093ef03fc0c84638de765b22ee0a46a3622b694ef8eb09c0fdd8f8e0712d26341005b097751af839d5a59f2949e53
  firebase_pn_key: AAAAK1R4_qE:APA91bHfn_BW-vAkjKWulUmrEHiU0kjG2t4W5SyVo30xzit8VXENwmfD59nHE07Hlr0YBm_7EBxbfQWLfyjsc55Qt4MBLqssNEMyIGgGubsRFRAy9LpV3n_PTy-7sOk_2x6JJnpjSfTv

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  firebase_pn_key: <%= ENV["FIREBASE_PN_KEY"] %>
